apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment-web.yaml
  - deployment-worker.yaml
  - service.yaml
  - ingress.yaml
  - hpa-web.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - job-migrate.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: santim-commerce
      app.kubernetes.io/managed-by: kustomize
