-- Hand-written, not generated by `prisma migrate dev --create-only`: an
-- earlier attempt at this migration (with an incorrect
-- answeredByUserId -> users FK, since fixed to answeredBySellerId ->
-- sellers) was applied to this local dev database, then rolled back by
-- hand — but Postgres has no ALTER TYPE ... DROP VALUE, so the
-- NotificationType enum here still has QUESTION_ANSWERED for real, even
-- though no migration file in this history explains how it got there.
-- IF NOT EXISTS makes the ADD VALUE line safe to run again regardless.

-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'QUESTION_ANSWERED';

-- CreateTable
CREATE TABLE "product_questions" (
    "id" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "askedByUserId" TEXT NOT NULL,
    "question" TEXT NOT NULL,
    "answer" TEXT,
    "answeredAt" TIMESTAMP(3),
    "answeredBySellerId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "product_questions_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "product_questions_productId_createdAt_idx" ON "product_questions"("productId", "createdAt");

-- AddForeignKey
ALTER TABLE "product_questions" ADD CONSTRAINT "product_questions_productId_fkey" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_questions" ADD CONSTRAINT "product_questions_askedByUserId_fkey" FOREIGN KEY ("askedByUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_questions" ADD CONSTRAINT "product_questions_answeredBySellerId_fkey" FOREIGN KEY ("answeredBySellerId") REFERENCES "sellers"("id") ON DELETE SET NULL ON UPDATE CASCADE;
